title: Nathanael Senjaya
url: "https://nathansenjaya.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/nathansenjaya"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://nathansenjaya.github.io"
 - name: "Resume"
   link: "resume.pdf"
